# Pico Users
#
#A hierarchical users and rights system plugin for [Pico CMS](https://github.com/picocms/Pico).
#
#- Login and logout
#- Unlimited users and hierarchical user groups
#- Simple rights management
#- Pages and directories restrictions
#- 403 Unauthorized error page
#- Twig variables and utilities for theming
#- API for other plugins (ex. [Pico Content Editor](https://github.com/nliautaud/pico-content-editor))
#
## Settings
#
#Users, rights and others settings can be defined in Pico config file.
#
#```yml
users:
    fakesbook: 
    editors:
        admins:
            root: 
rights:
    secret/infos: editors
    secret/infos/: editors/admins
    fakesbook: fakesbook
#```
#
### Users and groups
#
#The setting `users` is an array of user names and `bcrypt` hashed passwords.
#
#You can create groups of users by using sub-arrays, and nest groups to create hierarchical systems.
#
#Users are defined by their user path. In the previous example, the users `john` and `editors/admins/john` are two distinct users. "Admin John" will inherit the rights of its two groups, when "just John" don't have the rights of any group.
#
#### Rights
#
#The setting `rights` is a flat list of rules, associating a rule to a user or a group of users.
#
#> Note that you can target a specific path or all sub-paths by using or not a trailing slash.
#
#PicoUsers will use these rules as *rights to view pages*, but other plugins may define other meanings, like editing in [Pico Content Editor](https://github.com/nliautaud/pico-content-editor).
#
#```yml
rights:
    content/: editors
    PicoContentEditor/save: admins
#```
#